server:
  port: 8081

spring:
  application:
    name: resilience4j-demo  # Corrected application name

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all actuator endpoints
  endpoint:
    health:
      show-details: always  # Always show details in health endpoint
  health:
    circuitbreakers:
      enabled: true  # Enable circuit breaker health checks

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
